---
title:        OSHUG
subtitle:     Open Source Hardware User Group
description:  A group of people with an interest in open source hardware.
uri:          http://oshug.org/
email:        hello@oshug.org
lang:         en-gb
author:       oshug.org
license:
    title:   Creative Commons License
    uri:     http://creativecommons.org/licenses/by/3.0/

introduction: |
    <p>
    A group of people with a shared interest in 
    <a href="http://en.wikipedia.org/wiki/Open-source_hardware">Open Source Hardware</a>, 
    we hold regular meetings in and around London.
    We welcome suggestions for topics and speakers for future events 
    on the <a href="http://oshug.org/cgi-bin/mailman/listinfo/oshug">discussion list</a>.
    </p>

tags:
    - open-source
    - hardware
    - development
    - geek
    - tea

locations:
    Osmosoft:
        uri:       http://www.osmosoft.com/#[[Contact%20us]]
        street:    1a Broadway Street
        locality:  London
        postcode:  SW1H 0AY
        country:   UK
        latitude:  51.498325
        longitude: -0.134347

    London Hackspace:
        uri:       http://london.hackspace.org.uk/
        street:    Unit 24, Cremer Business Centre, 37 Cremer Street
        locality:  London
        postcode:  E2 8HD
        country:   UK
        latitude:  51.530746
        longitude: -0.076218

    BBC White City Media Centre:
        uri:       http://bbc.co.uk/
        street:    201 Wood Lane
        locality:  London
        postcode:  W12 7TQ
        country:   UK
        latitude:  51.513359
        longitude: -0.227874

    Skills Matter:
        uri:       http://skillsmatter.com/
        street:    116-120 Goswell Road
        locality:  London
        postcode:  EC1V 7DP
        country:   UK
        latitude:  51.525335
        longitude: -0.099056

    Centre for Creative Collaboration:
        uri:       http://www.creativecollaboration.org.uk/
        street:    16 Acton Street
        locality:  London
        postcode:  WC1X 9NG
        latitude:  51.529049
        longitude: -0.116436

    School of Engineering and Digital Arts:
        uri:    http://www.eda.kent.ac.uk/
        extendedaddress: Jennison Building
        street: The University of Kent
        locality: Canterbury
        region: Kent
        postcode: CT2 7NT
        latitude: 51.298383
        longitude: 1.064172

    The Birchcliffe Centre:
        uri:       http://pennineheritage.org.uk/projects/the-birchliffe-centre
        street:    Birchcliffe Road
        locality:  Hebden Bridge
        region:    West Yorkshire
        postcode:  HX7 8DG
        latitude:  53.743433
        country:   UK
        longitude: -2.008952

    Erlang Solutions:
        uri:       https://www.erlang-solutions.com/
        extendedaddress: New Loom House
        street:    101 Back Church Lane
        locality:  London
        postcode:  E1 1LU
        country:   UK
        latitude:  51.512889
        longitude: -0.067243

    Hebden Bridge Town Hall:
        uri:       http://www.hebdenbridgetownhall.org.uk/
        street:    St. George's Street
        locality:  Hebden Bridge
        postcode:  HX7 7BY
        country:   UK
        latitude:  53.742436
        longitude: -2.012918

    BCS London:
        uri:       http://www.bcs.org
        extendedaddress: 1st Floor, The Davidson Building
        street:    5 Southampton Street
        locality:  London
        postcode:  WC2E 7HA
        latitude:  51.510812
        longitude: -0.121733

    Owen Lecture Theatre:
        uri:       http://www.shu.ac.uk/eventservices/venues/owen-lecture-theatre
        extendedaddress: 1028 Owen Building, Sheffield Hallam University
        street:    Howard Street
        locality:  Sheffield
        postcode:  S1 1WB
        latitude:  53.379176
        longitude: -1.466163

    Fab Lab London:
        uri:       http://fablablondon.org/
        extendedaddress: Off Old Jewry
        street:    1 Frederickâ€™s Place
        locality:  London
        postcode:  EC2R 8AE
        latitude:  51.514194
        longitude: -0.091342
 
feeds:
    - atom

media:
    atom:
        title: Atom
        type: application/atom+xml

    yaml:
        title: YAML
        type: text/yaml;charset=utf-8

    xml:
        title: XML
        type: text/xml;charset=utf-8

    json:
        title: JSON
        type: application/json

    jsonp:
        title: JSONP
        type: application/javascript

# one line per-event
released:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - oshcamp
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - oshcamp2012
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - oshcamp2013
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - oshcamp2014
    - 36
    - 37
    - 38
    - 39
    - 40
    - 41
    - 42
    - oshcamp2015
    - 44
    - 45
    - 46
    - 47
    - nmiopen
    - 49
